[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
ignore = [
    # fxhash, wait for deps to scraper update
    "RUSTSEC-2025-0057",
]

[licenses]
confidence-threshold = 0.93
private = { ignore = true }
allow = [ 
    "Apache-2.0",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "OpenSSL",
    "Unicode-3.0",
    "Unicode-DFS-2016", 
]
exceptions = []

[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[bans]
multiple-versions = "warn"
highlight = "all"
skip = [
    { name = "windows-sys", version = "0.60.2" },
    { name = "windows_x86_64_msvc", version = "0.52.6" },
    { name = "windows_x86_64_gnu", version = "0.52.6" },
    { name = "windows-targets", version = "0.52.6" },
    { name = "windows-sys", version = "0.59.0" },
    { name = "cookie_store", version = "0.21.1" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [ "https://github.com/rust-lang/crates.io-index" ]
allow-git = []

[sources.allow-org]
github = [
    "nathaniel-daniel",
]
